---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.1

suites:
  - name: single
    run_list:
      - recipe[single::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
  - name: multiple
    run_list:
      - recipe[multiple::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
